import "./globals.css";
import Navigation from "./_components/Navigation";
import { Outfit } from "next/font/google";

import Spinner from "./_sub components/Spinner";
import Footer from "./_components/Footer";
import { Analytics } from "@vercel/analytics/next";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});
export const metadata = {
  title: "Anandhu Prasad | FullStack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0A0A0A] mx-auto">
        <Navigation />
        <main>{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
